### ISSUE TITLE
Option to display historical data for deleted characters

### ISSUE THREAD

**Issue by devjt2** [chrisfried/secret-scrublandeux#38]
Many Destiny players (such as myself) have deleted characters in addition to current characters. Can this historical data also be viewable?

I imagine that this application is gathering just the current list of active characters using this endpoint.
`https://www.bungie.net/Platform/Destiny2/1/Profile/{membershipID}/?components=100`

I believe that all of the historical data is there in the API for deleted characters. But I am not completely certain. I did find that there is an API to gather all characters at this location:  `https://www.bungie.net/Platform/Destiny2/1/Account/{membershipID}/Stats/?groups=General`

All characters, delete or not, are located in the response payload at: `Response.Characters`

**Comment by chrisfried** [comment]
@devjt2 Hypothetically, the Bungie calendar view should support deleted characters. However, I don't have any deleted characters on my account to test with. Mind checking it out?
