### ISSUE TITLE
Can't search by steamID

### ISSUE THREAD

**Issue by ironstrix** [chrisfried/secret-scrublandeux#5]
Sometimes searching a guardian's ingame name will not yield the proper results to find said player on PC. If it was possible to search via the player's steamID then you'd always be able to find the player you're looking for.

**Comment by ironstrix** [comment]
I appreciate the quick response! I figured I'd ask for this since our clan uses this tool all the time for checking out new applicants to see how they like to spend their time playing d2 to determine their fit for the clan. It really is invaluable to us and we appreciate your work. Thanks again.

**Comment by chrisfried** [comment]
In the short term, Guardian Theater uses a similar URL structure. You could login there, hit My Profile, and then copy the membership ID from the URL. Certainly not ideal, but it'll do the trick.

![image](https://user-images.githubusercontent.com/422381/67700161-aa44dc80-f96a-11e9-8812-3de2a4b26a2c.png)

**Comment by chrisfried** [comment]
There is now a Sign In button on the site that will allow circumvention of the search feature to reach your own profile.
